import mongoose, { Schema, Document } from 'mongoose';

export interface MembershipPlan {
  id: string;
  name: string;
  description?: string; // Description of the membership plan
  price: string; // e.g., "Free", "$19.99 / month"
  url: string; // Base Whop product page URL (affiliate link will be generated by appending ?a={username})
  isPremium?: boolean; // Whether this is a premium/paid plan
}

export type UserRole = 'owner' | 'admin' | 'member';

export interface IUser extends Document {
  alias: string;
  whopUserId: string;
  companyId?: string; // Company ID (manually entered, not auto-set from Whop)
  companyName?: string; // Company name (only for owners)
  companyDescription?: string; // Company description (only for owners)
  role: UserRole; // User role: owner, admin, or member
  whopName?: string; // Name of the Whop/company
  whopUsername?: string; // Username from Whop profile
  whopDisplayName?: string; // Display name from Whop profile
  whopAvatarUrl?: string; // Avatar URL from Whop profile
  whopWebhookUrl?: string; // Whop webhook URL for notifications
  discordWebhookUrl?: string; // Discord webhook URL for notifications
  notifyOnSettlement?: boolean; // Whether to send notifications when bets are settled
  membershipPlans?: MembershipPlan[]; // Array of membership plans for this Whop (only for owners)
  membershipUrl?: string; // Legacy: Primary membership URL (deprecated, use membershipPlans)
  optIn: boolean; // Only owners can opt-in to leaderboard
  stats: {
    winRate: number;
    roi: number;
    unitsPL: number;
    currentStreak: number;
    longestStreak: number;
  };
  createdAt: Date;
  updatedAt: Date;
}

const MembershipPlanSchema = new Schema<MembershipPlan>({
  id: { type: String, required: true },
  name: { type: String, required: true },
  description: { type: String },
  price: { type: String, required: true },
  url: { type: String, required: true },
  isPremium: { type: Boolean, default: false },
}, { _id: false });

const UserSchema = new Schema<IUser>({
  alias: { type: String, required: true, trim: true },
  whopUserId: { type: String, required: true, index: true },
  companyId: { type: String, index: true }, // Optional - must be manually entered
  companyName: { type: String, trim: true }, // Company name (only for owners)
  companyDescription: { type: String, trim: true }, // Company description (only for owners)
  role: { type: String, enum: ['owner', 'admin', 'member'], default: 'member', index: true },
  whopName: { type: String, trim: true },
  whopUsername: { type: String, trim: true },
  whopDisplayName: { type: String, trim: true },
  whopAvatarUrl: { type: String, trim: true },
  whopWebhookUrl: { type: String, trim: true },
  discordWebhookUrl: { type: String, trim: true },
  notifyOnSettlement: { type: Boolean, default: false },
  membershipPlans: { type: [MembershipPlanSchema], default: [] }, //only for owners
  membershipUrl: { type: String }, // Legacy field for backward compatibility
  optIn: { type: Boolean, default: false }, // Default false, only owners can opt-in
  stats: {
    winRate: { type: Number, default: 0 },
    roi: { type: Number, default: 0 },
    unitsPL: { type: Number, default: 0 },
    currentStreak: { type: Number, default: 0 },
    longestStreak: { type: Number, default: 0 },
  },
}, {
  timestamps: true,
});

// Compound indexes for efficient queries
UserSchema.index({ companyId: 1, whopUserId: 1 }, { unique: true, sparse: true }); // Unique user per company (sparse since companyId can be null)
UserSchema.index({ companyId: 1, role: 1 }, { unique: true, partialFilterExpression: { role: 'owner', companyId: { $exists: true, $ne: null } } }); // Only 1 owner per companyId
UserSchema.index({ companyId: 1, optIn: 1, 'stats.roi': -1, 'stats.winRate': -1 }); // For company-scoped leaderboard

export const User = (mongoose.models && mongoose.models.User) || mongoose.model<IUser>('User', UserSchema);

